dbt_ecommerce:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: ecommerce_user
      password: ecommerce_password
      port: 5432
      dbname: ecommerce_raw
      schema: marts
      threads: 4
      keepalives_idle: 0