version: 2

models:
  # ========== STAGING LAYER ==========
  - name: stg_usuarios
    description: "Usuarios sin transformaciones"
    columns:
      - name: usuario_id
        tests: [unique, not_null]
  
  - name: stg_productos
    description: "Productos sin transformaciones"
    columns:
      - name: producto_id
        tests: [unique, not_null]
  
  - name: stg_ordenes
    description: "Órdenes sin transformaciones"
    columns:
      - name: orden_id
        tests: [unique, not_null]
  
  - name: stg_detalle_ordenes
    description: "Líneas de orden"
  
  - name: stg_categorias
    description: "Categorías"
  
  - name: stg_metodos_pago
    description: "Métodos de pago"
  
  - name: stg_direcciones_envio
    description: "Direcciones de envío"
  
  - name: stg_resena_productos
    description: "Reseñas de productos"
  
  - name: stg_ordenes_metodos_pago
    description: "Pagos asociados a órdenes"

  # ========== INTERMEDIATE LAYER ==========
  - name: int_ordenes_detalle
    description: "Órdenes con detalle - JOIN limpio"
    columns:
      - name: orden_id
        tests: [not_null]
      - name: monto_linea
        description: "cantidad * precio_unitario"
  
  - name: int_cliente_completo
    description: "Usuarios con dirección completa"
    columns:
      - name: usuario_id
        tests: [unique, not_null]
  
  - name: int_producto_categoria
    description: "Productos con categoría"
    columns:
      - name: producto_id
        tests: [unique, not_null]
  
  - name: int_ordenes_pagos
    description: "Órdenes con métodos de pago"

  # ========== MARTS LAYER - HECHOS ==========
  - name: mart_hecho_ventas
    description: "Tabla de hechos - Granularidad: línea de orden (40k filas)"
    columns:
      - name: id_hecho_venta
        description: "PK auto-generada"
        tests: [unique, not_null]
      - name: orden_id
        description: "FK orden"
        tests: [not_null]
      - name: producto_id
        description: "FK producto"
        tests: [not_null]
      - name: usuario_id
        description: "FK cliente"
      - name: cantidad
        description: "Cantidad vendida"
        tests: [not_null]
      - name: monto_neto
        description: "Monto neto venta"
        tests: [not_null]

  - name: mart_hecho_pago
    description: "Tabla de hechos - Pagos (0 filas - sin datos)"
    columns:
      - name: id_hecho_pago
        description: "PK pago"
        tests: [unique, not_null]

  # ========== MARTS LAYER - DIMENSIONES ==========
  - name: mart_dim_cliente
    description: "Dimensión Cliente (SCD Type 2) - 1,000 filas"
    columns:
      - name: id_cliente
        description: "PK dimensión"
        tests: [unique, not_null]
      - name: correo_electronico
        description: "Email único"
        tests: [unique]
      - name: es_vigente
        description: "Flag registro vigente"
        tests: [not_null]
      - name: version
        description: "Versión SCD"

  - name: mart_dim_producto
    description: "Dimensión Producto (SCD Type 2) - 144 filas"
    columns:
      - name: id_producto
        description: "PK dimensión"
        tests: [unique, not_null]
      - name: nombre_producto
        tests: [not_null]
      - name: precio_actual
        tests: [not_null]

  - name: mart_dim_fecha
    description: "Dimensión Fecha (calendario) - 3,651 filas"
    columns:
      - name: id_fecha
        description: "PK YYYYMMDD"
        tests: [unique, not_null]
      - name: fecha
        description: "Fecha DATE"
        tests: [unique, not_null]
      - name: ano
        tests: [not_null]

  - name: mart_dim_ubicacion
    description: "Dimensión Geografía - 1,000 ubicaciones"
    columns:
      - name: id_ubicacion
        description: "PK dimensión"
        tests: [unique, not_null]
      - name: pais
        tests: [not_null]

  - name: mart_dim_metodo_pago
    description: "Dimensión Método de Pago - 0 filas"
    columns:
      - name: id_metodo_pago
        description: "PK dimensión"
        tests: [unique, not_null]

  # ========== KPIs & MÉTRICAS ==========
  - name: mart_kpi_ventas_diarias
    description: "KPI: Ventas diarias agregadas (342 días)"
    columns:
      - name: fecha
        description: "Fecha venta"
        tests: [unique]
      - name: total_ordenes
        description: "Cantidad de órdenes"
      - name: monto_total_vendido
        description: "Ingresos del día"
      - name: ticket_promedio
        description: "Promedio de venta"
      - name: clientes_unicos
        description: "Clientes únicos del día"

  - name: mart_kpi_productos_top
    description: "KPI: Performance de productos con ranking"
    columns:
      - name: id_producto
        tests: [unique]
      - name: total_vendido
        description: "Cantidad total vendida"
      - name: ranking_ventas
        description: "Ranking por volumen"
      - name: segmento_cliente
        description: "Segmentación: Premium/Gold/Silver/Bronze"

  - name: mart_kpi_clientes_segmentacion
    description: "KPI: Segmentación de clientes por gasto"
    columns:
      - name: id_cliente
        tests: [unique]
      - name: total_ordenes
        description: "Total compras cliente"
      - name: monto_total_gastado
        description: "Gasto acumulado"

  - name: mart_kpi_categorias_performance
    description: "KPI: Performance por categoría"
    columns:
      - name: categoria
        description: "Nombre categoría"
      - name: porcentaje_ventas_totales
        description: "% del total de ventas"